# capybara configuration
capybara:
  default:
      # url
#      host: https://test.salesforce.com/
      host: https://accounts.google.com
      # how long to wait for asynchronous processing to finish
      wait_time: 15
      # credentials
#      user: cst_analyst@jalasoft.com.aut02
#      password: Control123
      user: inter.prueba.pacata
      password: zoomadsl2010

drivers:
    - chrome

